name: Macro RSS Pipeline

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install requests feedparser

      - name: Run RSS Engine
        run: |
          python rss_notify.py

      - name: Commit alerts.json
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

          git add alerts.json seen.json

          git diff --cached --quiet || git commit -m "update alerts"

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
